module.exports = {
  "drinks": [
  {
  "idDrink": "12738",
  "strDrink": "Hot Chocolate to Die for",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Cocoa",
  "strIBA": null,
  "strAlcoholic": "Non alcoholic",
  "strGlass": "Coffee mug",
  "strInstructions": "Melt the chocolate, butter and vanilla in a double boiler. When just smooth stir in the cream.",
  "strInstructionsES": null,
  "strInstructionsDE": "Schokolade, Butter und Vanille in einem Doppelkocher schmelzen. Wenn es glatt ist, die Sahne unterrühren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Sciogliere il cioccolato, il burro e la vaniglia a bagnomaria.Quando risulterà liscio aggiungere la panna.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/0lrmjp1487603166.jpg",
  "strIngredient1": "Chocolate",
  "strIngredient2": "Butter",
  "strIngredient3": "Vanilla extract",
  "strIngredient4": "Half-and-half",
  "strIngredient5": "Marshmallows",
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "12 oz fine ",
  "strMeasure2": "1 tsp ",
  "strMeasure3": "1/2 tsp ",
  "strMeasure4": "1 cup ",
  "strMeasure5": "mini ",
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2017-02-20 15:06:06"
  },
  {
  "idDrink": "17006",
  "strDrink": "Kool First Aid",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Shot",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Shot glass",
  "strInstructions": "Add Kool Aid to a double shot glass, and top with rum. Slam and shoot.",
  "strInstructionsES": null,
  "strInstructionsDE": "Geben Sie Kool Aid in ein Doppelschnapsglas und füllen Sie es mit Rum. Knall und Schuss.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Aggiungi Kool-Aid, successivamente aggiungi il rum.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hfp6sv1503564824.jpg",
  "strIngredient1": "151 proof rum",
  "strIngredient2": "Kool-Aid",
  "strIngredient3": null,
  "strIngredient4": null,
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "2 oz light ",
  "strMeasure2": "1/2 tsp Tropical ",
  "strMeasure3": null,
  "strMeasure4": null,
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2017-08-24 09:53:44"
  },
  {
  "idDrink": "11117",
  "strDrink": "Blue Lagoon",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Highball glass",
  "strInstructions": "Pour vodka and curacao over ice in a highball glass. Fill with lemonade, top with the cherry, and serve.",
  "strInstructionsES": null,
  "strInstructionsDE": "Gießen Sie Wodka und Curacao in einem Highball-Glas über Eis. Mit Limonade füllen, mit der Kirsche verzieren und servieren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Versare la vodka e il curacao in un bicchiere highball. Aggiungi cubetti di ghiaccio. Riempi con la limonata, guarnisci con la ciliegia e servi.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5wm4zo1582579154.jpg",
  "strIngredient1": "Vodka",
  "strIngredient2": "Blue Curacao",
  "strIngredient3": "Lemonade",
  "strIngredient4": "Cherry",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "1 oz ",
  "strMeasure2": "1 oz ",
  "strMeasure3": null,
  "strMeasure4": null,
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "Yes",
  "dateModified": "2017-09-02 22:58:25"
  },
  {
  "idDrink": "11202",
  "strDrink": "Caipirinha",
  "strDrinkAlternate": null,
  "strTags": "ContemporaryClassic,IBA",
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": "Contemporary Classics",
  "strAlcoholic": "Alcoholic",
  "strGlass": "Old-fashioned glass",
  "strInstructions": "Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cachaça.",
  "strInstructionsES": null,
  "strInstructionsDE": "Limette und Zucker in ein old-fashioned Glas geben und vermengen (die beiden Zutaten mit einem Mixer oder einem Holzlöffel vermengen). Füllen Sie das Glas mit Eis und geben Sie den Cacha dazu.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Mettere il lime e lo zucchero nel bicchiere vecchio stile e pestare (schiacciare i due ingredienti insieme usando un pestello o un cucchiaio di legno).Riempi il bicchiere di ghiaccio e aggiungi la Cachaça.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg",
  "strIngredient1": "Sugar",
  "strIngredient2": "Lime",
  "strIngredient3": "Cachaca",
  "strIngredient4": null,
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "2 tsp",
  "strMeasure2": "1 ",
  "strMeasure3": "2 1/2 oz ",
  "strMeasure4": null,
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": "https://www.thecocktaildb.com/drink/11202-Caipirinha",
  "strImageAttribution": "TheCocktailDB.com",
  "strCreativeCommonsConfirmed": "Yes",
  "dateModified": "2016-07-21 09:42:01"
  },
  {
  "idDrink": "11993",
  "strDrink": "Quentin",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Cocktail glass",
  "strInstructions": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg.",
  "strInstructionsES": null,
  "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Rum, Kahlua und Sahne mischen. Gut schütteln. In ein Cocktailglas abseihen und mit der Muskatnuss garnieren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum, il Kahlua e la panna. Filtrare in una coppetta da cocktail e guarnire con la noce moscata. Agitare bene.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/spxtqp1478963398.jpg",
  "strIngredient1": "Dark rum",
  "strIngredient2": "Kahlua",
  "strIngredient3": "Light cream",
  "strIngredient4": "Nutmeg",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "1 1/2 oz ",
  "strMeasure2": "1/2 oz ",
  "strMeasure3": "1 oz ",
  "strMeasure4": "1/8 tsp grated ",
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2016-11-12 15:09:58"
  },
  {
  "idDrink": "14978",
  "strDrink": "Rum Punch",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Punch / Party Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Punch bowl",
  "strInstructions": "Mix all ingredients in a punch bowl and serve.",
  "strInstructionsES": null,
  "strInstructionsDE": "Alle Zutaten in einer Bowle mischen und servieren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Mescolare tutti gli ingredienti in una ciotola da punch e servire.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wyrsxu1441554538.jpg",
  "strIngredient1": "Rum",
  "strIngredient2": "Ginger ale",
  "strIngredient3": "Fruit punch",
  "strIngredient4": "Orange juice",
  "strIngredient5": "Ice",
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "mikey bottle ",
  "strMeasure2": "large bottle ",
  "strMeasure3": "355 ml frozen ",
  "strMeasure4": "355 ml frozen ",
  "strMeasure5": "crushed ",
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2015-09-06 16:48:58"
  },
  {
  "idDrink": "11145",
  "strDrink": "Classic Old-Fashioned",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Old-fashioned glass",
  "strInstructions": "In an old-fashioned glass, muddle the bitters and water into the sugar cube, using the back of a teaspoon. Almost fill the glass with ice cubes and add the bourbon. Garnish with the orange slice and the cherry. Serve with a swizzle stick.",
  "strInstructionsES": null,
  "strInstructionsDE": "In einem old-fashioned Glas die Bitter und das Wasser mit der Rückseite eines Teelöffels in den Zuckerwürfel mischen. Füllen Sie das Glas fast mit Eiswürfeln und fügen Sie den Bourbon hinzu. Mit der Orangenscheibe und der Kirsche garnieren. Mit einem Quirlstab servieren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "In un bicchiere vecchio stile, mescola il bitter e l'acqua nella zolletta di zucchero. Riempite quasi il bicchiere di cubetti di ghiaccio e aggiungete il bourbon. Servire con un bastoncino di zucchero. Guarnire con la fetta d'arancia e la ciliegia.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/w8cxqv1582485254.jpg",
  "strIngredient1": "Bitters",
  "strIngredient2": "Water",
  "strIngredient3": "Sugar",
  "strIngredient4": "Bourbon",
  "strIngredient5": "Orange",
  "strIngredient6": "Maraschino cherry",
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "3 dashes ",
  "strMeasure2": "1 tsp ",
  "strMeasure3": "1 ",
  "strMeasure4": "3 oz ",
  "strMeasure5": "1 ",
  "strMeasure6": "1 ",
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "Yes",
  "dateModified": "2017-09-02 16:29:33"
  },
  {
  "idDrink": "14360",
  "strDrink": "Absolut Sex",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Shot",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Old-fashioned glass",
  "strInstructions": "Shake Absolut Kurant, Midori, and Cranberry juice in shaker with ice: Strain into rocks glass: Splash of seven on top.Absolut Sex.",
  "strInstructionsES": null,
  "strInstructionsDE": "Absolut Kurant, Midori und Preiselbeersaft im Shaker mit Eis schütteln: In ein Rocks Glas abseihen: Ein Spritzer von 7 oben drauf. Absoluter Sex.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Shakerare Absolut Kurant, Midori e il succo di mirtillo rosso in uno shaker con ghiaccio",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xtrvtx1472668436.jpg",
  "strIngredient1": "Absolut Kurant",
  "strIngredient2": "Midori melon liqueur",
  "strIngredient3": "Cranberry juice",
  "strIngredient4": "Sprite",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "3/4 oz ",
  "strMeasure2": "3/4 oz ",
  "strMeasure3": "1 oz ",
  "strMeasure4": "1 splash ",
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2016-08-31 19:33:56"
  },
  {
  "idDrink": "13200",
  "strDrink": "Owen's Grandmother's Revenge",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Highball glass",
  "strInstructions": "Add ingredients and mix in blender.",
  "strInstructionsES": null,
  "strInstructionsDE": "Zutaten im Mixer vermengen.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Aggiungere gli ingredienti e mescola nel frullatore.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/0wt4uo1503565321.jpg",
  "strIngredient1": "Whiskey",
  "strIngredient2": "Beer",
  "strIngredient3": "Lemonade",
  "strIngredient4": "Ice",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "12 oz ",
  "strMeasure2": "12 oz ",
  "strMeasure3": "12 oz frozen ",
  "strMeasure4": "1 cup crushed ",
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2017-08-24 10:02:02"
  },
  {
  "idDrink": "12864",
  "strDrink": "Apple Cider Punch",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Punch / Party Drink",
  "strIBA": null,
  "strAlcoholic": "Optional alcohol",
  "strGlass": "Collins Glass",
  "strInstructions": "If you use the whole all spice and cloves, tie them in cheesecloth. Heat the mixture. Stir occasionally. If you want an alcoholic drink, rum would be nice.",
  "strInstructionsES": null,
  "strInstructionsDE": "Wenn du das ganze Gewürz und die Nelken verwendest, bindest du sie in ein Seihtuch. Die Mischung erhitzen. Gelegentlich umrühren. Wenn du ein alkoholisches Getränk willst, wäre Rum schön.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Versa tutto in un pentolino tranne spezie e chiodi di garofano, legali in una garza e tienili in ammollo. Riscalda la miscela. Mescola di tanto in tanto. Se vuoi una bevanda alcolica puoi aggiungere un po’ di Rum.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xrqxuv1454513218.jpg",
  "strIngredient1": "Apple cider",
  "strIngredient2": "Brown sugar",
  "strIngredient3": "Lemonade",
  "strIngredient4": "Orange juice",
  "strIngredient5": "Cloves",
  "strIngredient6": "Allspice",
  "strIngredient7": "Nutmeg",
  "strIngredient8": "Cinnamon",
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "4 qt ",
  "strMeasure2": "1 cup ",
  "strMeasure3": "6 oz frozen ",
  "strMeasure4": "6 oz frozen ",
  "strMeasure5": "6 whole ",
  "strMeasure6": "6 whole ",
  "strMeasure7": "1 tsp ground ",
  "strMeasure8": "3 sticks ",
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2016-02-03 15:26:58"
  }
  ]
  }